worker_processes  1;

events { worker_connections  1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 8080;
        server_name _;
        client_max_body_size 20M;

        root /var/www/html/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            include        fastcgi_params;
            fastcgi_param  HTTPS on;
            fastcgi_param  HTTP_X_FORWARDED_PROTO https;
            fastcgi_param  HTTP_X_FORWARDED_SSL on;
            fastcgi_param  SERVER_PORT 443;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param  PATH_INFO $fastcgi_path_info;
        }

        location = /livewire/livewire.min.js {
            rewrite ^ /livewire/livewire.js last;
        }
        location ^~ /livewire/ {
            try_files $uri $uri/ /index.php?$query_string;
        }
        location ~* \.(css|js|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
            expires 7d;
            add_header Cache-Control "public, max-age=604800";
            access_log off;
        }
    }
}
